---------------------------------------------------------------------------
-- Author ..... : M. Armaghan Saqib
-- EMail ...... : armaghan@yahoo.com
-- Internet ... : http://www.geocities.com/armaghan/
--
-- Purpose .... : (one line description of this script)
-- Date ....... : 24-05-15 14:20:39
-- Generated by SQL PlusPlus
---------------------------------------------------------------------------
DROP TRIGGER a$sec_users_biud;
DROP TRIGGER ap_vendors_biud;
DROP TRIGGER ccard_trg;
DROP TRIGGER gl_je_header_br;
DROP TRIGGER gl_je_lines_br;
DROP TRIGGER gl_journal_br;
DROP TRIGGER hc_advances_as;
DROP TRIGGER hc_advances_br;
DROP TRIGGER hc_advances_bs;
DROP TRIGGER hc_advances_detail_as;
DROP TRIGGER hc_advances_detail_br;
DROP TRIGGER hc_advances_detail_bs;
DROP TRIGGER hc_cc_types_as;
DROP TRIGGER hc_charges_as;
DROP TRIGGER hc_charges_br;
DROP TRIGGER hc_charges_bs;
DROP TRIGGER hc_charge_codes_br;
DROP TRIGGER hc_companies_br;
DROP TRIGGER hc_companies_rates_br;
DROP TRIGGER hc_companies_visits_trg;
DROP TRIGGER hc_fb_items_br;
DROP TRIGGER hc_fb_sale_as;
DROP TRIGGER hc_fb_sale_br;
DROP TRIGGER hc_fb_sale_bs;
DROP TRIGGER hc_fb_sale_lines_br;
DROP TRIGGER hc_hk_activity_br;
DROP TRIGGER hc_invoices_as;
DROP TRIGGER hc_invoices_br;
DROP TRIGGER hc_invoices_bs;
DROP TRIGGER hc_invoices_detail_br;
DROP TRIGGER hc_night_posting_log_br;
DROP TRIGGER hc_receipts_as;
DROP TRIGGER hc_receipts_br;
DROP TRIGGER hc_receipts_bs;
DROP TRIGGER hc_receipts_detail_as;
DROP TRIGGER hc_receipts_detail_br;
DROP TRIGGER hc_res_as;
DROP TRIGGER hc_res_br;
DROP TRIGGER hc_res_bs;
DROP TRIGGER hc_rooms_br;
DROP TRIGGER hc_room_change_log_as;
DROP TRIGGER hc_room_change_log_br;
DROP TRIGGER hc_room_change_log_bs;
DROP TRIGGER hc_room_rate_change_log_br;
DROP TRIGGER hc_room_rate_change_log_bs;
DROP TRIGGER hr_emp_trg;
DROP TRIGGER hr_lea_br;
DROP TRIGGER hr_sal_br;
DROP TRIGGER ic_items_br;
DROP TRIGGER ic_items_locs_br;
DROP TRIGGER ic_trans_header_tmp_br;
DROP TRIGGER ic_trans_lines_tmp_br;
DROP TRIGGER po_lines_br;
DROP TRIGGER pr_lines_br;
DROP TRIGGER trg1_a$cols;
DROP TRIGGER trg1_a$menu;
DROP TRIGGER trg1_a$sec_users_priv;
DROP TRIGGER trg1_banquet_lines;
DROP TRIGGER trg1_hc_reports;
DROP TRIGGER trg1_hc_reports_detail;
DROP TRIGGER trg1_notes;
DROP TRIGGER trg_hc_fb_recipies;
